### ISSUE TITLE
Use Action<T> from Vert.x codebase?

### ISSUE THREAD

**Issue by aschrijver** [jtruelove/vertx-util#9]
Just wanted to say: nice project this one, thanks! Just found it. This kind of common stuff is really useful and I have recently added an issue on the wishlist for a `vertx-common` project. See: https://github.com/vert-x3/issues/issues/164

One thing I noted: Did you create the `Action<T>` class, because the Vert.x one is in an internal implementation class (`io.vertx.core.impl.Action`)?

This is a good example of something that could be in `vertx-common`.

**Comment by jtruelove** [comment]
Yes if my memory serves me correctly I did. It's odd java doesn't supply something in their func namespace more like this.

**Comment by aschrijver** [comment]
Thanks. I have mentioned this as an example to add to the vertx-common module.
